//This is a simple Java program

//public class Simple
//{
//   public static void main(String[] args)
//   {
      //System.out.print("These lines will be ");
      //System.out.print("printed on ");//Statement
      //System.out.println("the same line.");
      //System.out.print("These are our top sellers:\n");
      //System.out.print("\tComputer games\n\tCoffee\n");
      //System.out.print("\tAspirin");
//   }
//}

//public class Variable
//{
//   public static void main(String[]args)
//   {
//      //int value;
      
      //value = 5;
      //System.out.println("Hello " + "World");
      //System.out.println("The value is: " + 5);
      //System.out.println("The value is: " + value);
      //System.out.println("The value is: " + '\n' + 5);
      //.out.println("This line is too long and now it has spanned more than one line, which will cause a syntax error to be generated by the compiler.");
      //System.out.println("These lines are " + "now ok and will not " + "cause the error as before.");
      //System.out.println("We can join a string to " + "a number like this: " + 5);
      //System.out.println("The following will be printed " + 
//                         "in a tabbed format: " +
//                         "\n\tFirst = " + 5 * 6 + ", " +
//                         "\n\tSecond = " + (6 + 4) + "," +
//                         "\n\tThird = " + 16.7 + ".");
//   }
//}

//public class Initialize
//{
//   public static void main(String[] args)
//   {
      //int month = 2, days = 28;
      
      //System.out.println("Month " + month + " has " + days + " days.");
//      int w = 5;
//      int x = 4;
//      int y = 8;
//      int z = 2;
//      int result;
//      
//    System.out.println(result = x + y);
//      System.out.println(result = z * 2);
//      System.out.println(result = y / x);
//      System.out.println(result = y - z);
//      System.out.println(result = w % 2);
//   }
//}
//import java.util.Scanner; //Needed for the Scanner in class
//public class ScannerExample
//{
//   public static void main(String[]args)
//   {
//      String name; //To hold a name
//      //Create a Scanner object to read input.
//      Scanner keyboard = new Scanner(System.in);
//      
//      // Get the user's name
//      System.out.print("What's your name");
//      name = keyboard.nextLine();
//      
//      System.out.print("How many hours do you work " + name + "?");
//      int hour = keyboard.nextInt();
//      
//      System.out.print("How much do you get paid an hour " + name + "?");
//      int wage = keyboard.nextInt();
//      
//      int result = wage*hour;
//      System.out.println("Hi " + name + "! \nYou work for " + hour + " hours and receive $" + wage + " hourly.\n Your gross pay daily is $" + result + "!\n Go head and make that money!");
//      
//   }
//}
import java.util.Scanner;

public class reviewJava
{
   public static void main(String[]args)
   {
      String name;
      Scanner keyboard = new Scanner(System.in);
      
      System.out.print("Name:");
      String user = keyboard.nextLine();
      
      System.out.print("Age:");
      int age = keyboard.nextInt();
      keyboard.nextLine();
      
      System.out.print("High School you graduated from:");
      String hschool = keyboard.nextLine();
      
      System.out.print("High School GPA:");
      float gpa = keyboard.nextFloat();
      keyboard.nextLine();
      
      System.out.print("University to Attend:");
      String college = keyboard.nextLine();;
      
      System.out.print("Major:");
      String major = keyboard.nextLine();
      
      System.out.print("Pick a number:");
      int num1 = keyboard.nextInt();
      keyboard.nextLine();
      
      System.out.print("Pick another number:");
      int num2 = keyboard.nextInt();
      keyboard.nextLine();
      
      System.out.print("Pick the last number:");
      int num3 = keyboard.nextInt();
      keyboard.nextLine();
      
      System.out.print("Pick a decimal point:");
      float dec1 = keyboard.nextFloat();
      keyboard.nextLine();
      
      System.out.print("Pick another decimal point:");
      float dec2 = keyboard.nextFloat();
      keyboard.nextLine();
      
      int result1 = num1 + num2 + num3;
      float result2 = dec1 + dec2;
      float result3 = result1 + result2;
      
      float result4 = num1 * num2 * dec1;
      float result5 = num1 / (num2 * dec1);
      
      System.out.println(user + "\n" + age + "\n" + hschool + "\n" + gpa + "\n" + college + "\n" + major
                         + "\n" + result1 + "\n" + result2 + "\n" + result3 + "\n" + result4 + "\n" + result5);
      }
}
